[package]
name = "yubikey_fido2_teste"
version = "0.1.0"
edition = "2024"

[dependencies]
ctap-hid-fido2 = "3.5.5"
anyhow = "1.0.99"
rpassword = "7.3.1"
hex = "0.4"
base64 = "0.22"
aes-gcm = "0.10"
rand = "0.9.2" 